import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export function Home({currencies}: any) {
  return (
    <div>
      <Head>
        <title>Currency Converter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container d-flex flex-column align-items-center text-center mt-5">
        <h1>Currency Converter</h1>
        <form action="">
          <div className="form-group">
            <label htmlFor="" className="form-label">Valor</label>
            <input className='form-control' type="number" name="value" />
          </div>

          <div className="form-group">
            <label htmlFor="" className="form-label">Converter de:</label>
            <select className='form-control' name="" id="">
              <option value="">Selecione uma moeda</option>
              {
                currencies.map((currency: any) => (
                  <option key={currency[0]} value={currency[0]}>{currency[1]}</option>
                ))
              }
            </select>
          </div>

          <div className="form-group">
            <label htmlFor="" className="form-label">Converter para:</label>
            <select className='form-control' name="" id="">
              <option value="">Selecione uma moeda</option>
              {
                currencies.map((currency: any) => (
                  <option key={currency[0]} value={currency[0]}>{currency[1]}</option>
                ))
              }
            </select>
          </div>

          <button type='button' className="btn btn-md btn-primary mt-5">Converter</button>
        </form>
      </div>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch(`https://economia.awesomeapi.com.br/json/available/uniq`)
  const data = await res.json()
  const currencies = Object.entries(data)
  //console.log(currencies)
  return { props: { currencies } }
}

export default Home
